// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: simple.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Simple.Grpc {
  public static partial class SimpleService
  {
    static readonly string __ServiceName = "simple.SimpleService";

    static readonly grpc::Marshaller<global::Simple.Grpc.SimpleRequest> __Marshaller_simple_SimpleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Simple.Grpc.SimpleRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Simple.Grpc.SimpleResponse> __Marshaller_simple_SimpleResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Simple.Grpc.SimpleResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Simple.Grpc.SimpleRequest, global::Simple.Grpc.SimpleResponse> __Method_SimpleSend = new grpc::Method<global::Simple.Grpc.SimpleRequest, global::Simple.Grpc.SimpleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SimpleSend",
        __Marshaller_simple_SimpleRequest,
        __Marshaller_simple_SimpleResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Simple.Grpc.SimpleReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SimpleService</summary>
    [grpc::BindServiceMethod(typeof(SimpleService), "BindService")]
    public abstract partial class SimpleServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Simple.Grpc.SimpleResponse> SimpleSend(global::Simple.Grpc.SimpleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SimpleService</summary>
    public partial class SimpleServiceClient : grpc::ClientBase<SimpleServiceClient>
    {
      /// <summary>Creates a new client for SimpleService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SimpleServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SimpleService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SimpleServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SimpleServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SimpleServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Simple.Grpc.SimpleResponse SimpleSend(global::Simple.Grpc.SimpleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SimpleSend(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Simple.Grpc.SimpleResponse SimpleSend(global::Simple.Grpc.SimpleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SimpleSend, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Simple.Grpc.SimpleResponse> SimpleSendAsync(global::Simple.Grpc.SimpleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SimpleSendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Simple.Grpc.SimpleResponse> SimpleSendAsync(global::Simple.Grpc.SimpleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SimpleSend, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SimpleServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SimpleServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SimpleServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SimpleSend, serviceImpl.SimpleSend).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SimpleServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SimpleSend, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Simple.Grpc.SimpleRequest, global::Simple.Grpc.SimpleResponse>(serviceImpl.SimpleSend));
    }

  }
}
#endregion
