// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: simplechat.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Simplechat {
  public static partial class SimpleChat
  {
    static readonly string __ServiceName = "simplechat.SimpleChat";

    static readonly grpc::Marshaller<global::Simplechat.SendRequest> __Marshaller_simplechat_SendRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Simplechat.SendRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Simplechat.SendResult> __Marshaller_simplechat_SendResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Simplechat.SendResult.Parser.ParseFrom);

    static readonly grpc::Method<global::Simplechat.SendRequest, global::Simplechat.SendResult> __Method_SendMessage = new grpc::Method<global::Simplechat.SendRequest, global::Simplechat.SendResult>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "SendMessage",
        __Marshaller_simplechat_SendRequest,
        __Marshaller_simplechat_SendResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Simplechat.SimplechatReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SimpleChat</summary>
    [grpc::BindServiceMethod(typeof(SimpleChat), "BindService")]
    public abstract partial class SimpleChatBase
    {
      /// <summary>
      /// Send message from a client to server
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Simplechat.SendResult> SendMessage(grpc::IAsyncStreamReader<global::Simplechat.SendRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SimpleChat</summary>
    public partial class SimpleChatClient : grpc::ClientBase<SimpleChatClient>
    {
      /// <summary>Creates a new client for SimpleChat</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SimpleChatClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SimpleChat that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SimpleChatClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SimpleChatClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SimpleChatClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Send message from a client to server
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncClientStreamingCall<global::Simplechat.SendRequest, global::Simplechat.SendResult> SendMessage(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendMessage(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Send message from a client to server
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncClientStreamingCall<global::Simplechat.SendRequest, global::Simplechat.SendResult> SendMessage(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_SendMessage, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SimpleChatClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SimpleChatClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SimpleChatBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SendMessage, serviceImpl.SendMessage).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SimpleChatBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SendMessage, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Simplechat.SendRequest, global::Simplechat.SendResult>(serviceImpl.SendMessage));
    }

  }
}
#endregion
